# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'App.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 2000)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(480, 160, 751, 731))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.functionsBox = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.functionsBox.setContentsMargins(0, 0, 0, 0)
        self.functionsBox.setObjectName("functionsBox")
        self.xLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.xLabel.setObjectName("xLabel")
        self.functionsBox.addWidget(self.xLabel, 12, 4, 1, 1)
        self.p2Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.p2Label.setObjectName("p2Label")
        self.functionsBox.addWidget(self.p2Label, 14, 3, 1, 1)
        self.resultedImageChangeScaleButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.resultedImageChangeScaleButton.setObjectName("resultedImageChangeScaleButton")
        self.functionsBox.addWidget(self.resultedImageChangeScaleButton, 8, 5, 1, 1)
        self.firstImageChangeScaleButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.firstImageChangeScaleButton.setObjectName("firstImageChangeScaleButton")
        self.functionsBox.addWidget(self.firstImageChangeScaleButton, 6, 5, 1, 1)
        self.p3Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.p3Label.setObjectName("p3Label")
        self.functionsBox.addWidget(self.p3Label, 15, 3, 1, 1)
        self.p3Y = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p3Y.setObjectName("p3Y")
        self.functionsBox.addWidget(self.p3Y, 15, 5, 1, 1)
        self.changeScaleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.changeScaleLabel.setObjectName("changeScaleLabel")
        self.functionsBox.addWidget(self.changeScaleLabel, 5, 0, 1, 6)
        self.yLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.yLabel.setObjectName("yLabel")
        self.functionsBox.addWidget(self.yLabel, 12, 5, 1, 1)
        self.firstImageScale = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.firstImageScale.setObjectName("firstImageScale")
        self.functionsBox.addWidget(self.firstImageScale, 6, 1, 1, 4)
        self.p2Y = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p2Y.setObjectName("p2Y")
        self.functionsBox.addWidget(self.p2Y, 14, 5, 1, 1)
        self.p1X = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p1X.setObjectName("p1X")
        self.functionsBox.addWidget(self.p1X, 13, 4, 1, 1)
        self.p1Y = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p1Y.setObjectName("p1Y")
        self.functionsBox.addWidget(self.p1Y, 13, 5, 1, 1)
        self.p2X = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p2X.setObjectName("p2X")
        self.functionsBox.addWidget(self.p2X, 14, 4, 1, 1)
        self.secondImageChangeScaleButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.secondImageChangeScaleButton.setObjectName("secondImageChangeScaleButton")
        self.functionsBox.addWidget(self.secondImageChangeScaleButton, 7, 5, 1, 1)
        self.cropImagesLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cropImagesLabel.setObjectName("cropImagesLabel")
        self.functionsBox.addWidget(self.cropImagesLabel, 0, 0, 1, 6)
        self.p1Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.p1Label.setObjectName("p1Label")
        self.functionsBox.addWidget(self.p1Label, 13, 3, 1, 1)
        self.imposingTypeNormal = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.imposingTypeNormal.setObjectName("imposingTypeNormal")
        self.functionsBox.addWidget(self.imposingTypeNormal, 12, 1, 4, 1)
        self.imposingType3Points = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.imposingType3Points.setObjectName("imposingType3Points")
        self.functionsBox.addWidget(self.imposingType3Points, 12, 2, 4, 1)
        self.firstImageCropY1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.firstImageCropY1.setObjectName("firstImageCropY1")
        self.functionsBox.addWidget(self.firstImageCropY1, 2, 2, 1, 1)
        self.firstImageCropX2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.firstImageCropX2.setObjectName("firstImageCropX2")
        self.functionsBox.addWidget(self.firstImageCropX2, 2, 3, 1, 1)
        self.typrLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.typrLabel.setObjectName("typrLabel")
        self.functionsBox.addWidget(self.typrLabel, 12, 0, 4, 1)
        self.saturation = QtWidgets.QSlider(self.gridLayoutWidget)
        self.saturation.setOrientation(QtCore.Qt.Horizontal)
        self.saturation.setObjectName("saturation")
        self.functionsBox.addWidget(self.saturation, 11, 1, 1, 5)
        self.secondImageCropY2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secondImageCropY2.setObjectName("secondImageCropY2")
        self.functionsBox.addWidget(self.secondImageCropY2, 3, 4, 1, 1)
        self.imposingParametrsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.imposingParametrsLabel.setObjectName("imposingParametrsLabel")
        self.functionsBox.addWidget(self.imposingParametrsLabel, 9, 0, 1, 6)
        self.secondImageScale = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.secondImageScale.setObjectName("secondImageScale")
        self.functionsBox.addWidget(self.secondImageScale, 7, 1, 1, 4)
        self.secondImageCropX2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secondImageCropX2.setObjectName("secondImageCropX2")
        self.functionsBox.addWidget(self.secondImageCropX2, 3, 3, 1, 1)
        self.firstImageCropButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.firstImageCropButton.setObjectName("firstImageCropButton")
        self.functionsBox.addWidget(self.firstImageCropButton, 2, 5, 1, 1)
        self.y1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.y1.setObjectName("y1")
        self.functionsBox.addWidget(self.y1, 1, 2, 1, 1)
        self.y2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.y2.setObjectName("y2")
        self.functionsBox.addWidget(self.y2, 1, 4, 1, 1)
        self.x2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.x2.setObjectName("x2")
        self.functionsBox.addWidget(self.x2, 1, 3, 1, 1)
        self.saturationLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.saturationLabel.setObjectName("saturationLabel")
        self.functionsBox.addWidget(self.saturationLabel, 11, 0, 1, 1)
        self.resultedImageScaleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.resultedImageScaleLabel.setObjectName("resultedImageScaleLabel")
        self.functionsBox.addWidget(self.resultedImageScaleLabel, 8, 0, 1, 1)
        self.secondImageScaleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.secondImageScaleLabel.setObjectName("secondImageScaleLabel")
        self.functionsBox.addWidget(self.secondImageScaleLabel, 7, 0, 1, 1)
        self.aplhaChanelLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.aplhaChanelLabel.setObjectName("aplhaChanelLabel")
        self.functionsBox.addWidget(self.aplhaChanelLabel, 10, 0, 1, 1)
        self.firstImageScaleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.firstImageScaleLabel.setObjectName("firstImageScaleLabel")
        self.functionsBox.addWidget(self.firstImageScaleLabel, 6, 0, 1, 1)
        self.resultedImageCropY2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.resultedImageCropY2.setObjectName("resultedImageCropY2")
        self.functionsBox.addWidget(self.resultedImageCropY2, 4, 4, 1, 1)
        self.x1Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.x1Label.setObjectName("x1Label")
        self.functionsBox.addWidget(self.x1Label, 1, 1, 1, 1)
        self.firstImageCropY2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.firstImageCropY2.setObjectName("firstImageCropY2")
        self.functionsBox.addWidget(self.firstImageCropY2, 2, 4, 1, 1)
        self.p3X = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p3X.setObjectName("p3X")
        self.functionsBox.addWidget(self.p3X, 15, 4, 1, 1)
        self.firstImageCropX1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.firstImageCropX1.setObjectName("firstImageCropX1")
        self.functionsBox.addWidget(self.firstImageCropX1, 2, 1, 1, 1)
        self.secondImageCropButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.secondImageCropButton.setObjectName("secondImageCropButton")
        self.functionsBox.addWidget(self.secondImageCropButton, 3, 5, 1, 1)
        self.resultedImageCropY1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.resultedImageCropY1.setObjectName("resultedImageCropY1")
        self.functionsBox.addWidget(self.resultedImageCropY1, 4, 2, 1, 1)
        self.firstImageCropLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.firstImageCropLabel.setObjectName("firstImageCropLabel")
        self.functionsBox.addWidget(self.firstImageCropLabel, 2, 0, 1, 1)
        self.resultedImageCropX1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.resultedImageCropX1.setObjectName("resultedImageCropX1")
        self.functionsBox.addWidget(self.resultedImageCropX1, 4, 1, 1, 1)
        self.resultedImageCropX2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.resultedImageCropX2.setObjectName("resultedImageCropX2")
        self.functionsBox.addWidget(self.resultedImageCropX2, 4, 3, 1, 1)
        self.resuledImageCropLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.resuledImageCropLabel.setObjectName("resuledImageCropLabel")
        self.functionsBox.addWidget(self.resuledImageCropLabel, 4, 0, 1, 1)
        self.secondImageCropX1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secondImageCropX1.setObjectName("secondImageCropX1")
        self.functionsBox.addWidget(self.secondImageCropX1, 3, 1, 1, 1)
        self.secondImageCropLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.secondImageCropLabel.setObjectName("secondImageCropLabel")
        self.functionsBox.addWidget(self.secondImageCropLabel, 3, 0, 1, 1)
        self.secondImageCropY1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.secondImageCropY1.setObjectName("secondImageCropY1")
        self.functionsBox.addWidget(self.secondImageCropY1, 3, 2, 1, 1)
        self.resultedImageScale = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.resultedImageScale.setObjectName("resultedImageScale")
        self.functionsBox.addWidget(self.resultedImageScale, 8, 1, 1, 4)
        self.resultedImageCropButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.resultedImageCropButton.setObjectName("resultedImageCropButton")
        self.functionsBox.addWidget(self.resultedImageCropButton, 4, 5, 1, 1)
        self.alphaChanel = QtWidgets.QSlider(self.gridLayoutWidget)
        self.alphaChanel.setOrientation(QtCore.Qt.Horizontal)
        self.alphaChanel.setObjectName("alphaChanel")
        self.functionsBox.addWidget(self.alphaChanel, 10, 1, 1, 5)
        self.image2 = QtWidgets.QLabel(self.centralwidget)
        self.image2.setGeometry(QtCore.QRect(10, 570, 191, 211))
        self.image2.setObjectName("image2")
        self.image2Label = QtWidgets.QLabel(self.centralwidget)
        self.image2Label.setGeometry(QtCore.QRect(10, 530, 121, 21))
        self.image2Label.setObjectName("image2Label")
        self.image1 = QtWidgets.QLabel(self.centralwidget)
        self.image1.setGeometry(QtCore.QRect(10, 200, 229, 212))
        self.image1.setObjectName("image1")
        self.image1Label = QtWidgets.QLabel(self.centralwidget)
        self.image1Label.setGeometry(QtCore.QRect(10, 140, 51, 31))
        self.image1Label.setObjectName("image1Label")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 861, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.file1pathLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.file1pathLabel.setObjectName("file1pathLabel")
        self.gridLayout.addWidget(self.file1pathLabel, 0, 0, 1, 1)
        self.file1Path = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.file1Path.setObjectName("file1Path")
        self.gridLayout.addWidget(self.file1Path, 0, 1, 1, 1)
        self.file2path = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.file2path.setObjectName("file2path")
        self.gridLayout.addWidget(self.file2path, 1, 1, 1, 1)
        self.loadFilesButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.loadFilesButton.setObjectName("loadFilesButton")
        self.gridLayout.addWidget(self.loadFilesButton, 2, 1, 1, 1)
        self.file1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.file1.setObjectName("file1")
        self.gridLayout.addWidget(self.file1, 1, 0, 1, 1)
        self.file1searchButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.file1searchButton.setObjectName("file1searchButton")
        self.gridLayout.addWidget(self.file1searchButton, 0, 2, 1, 1)
        self.file2searchButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.file2searchButton.setObjectName("file2searchButton")
        self.gridLayout.addWidget(self.file2searchButton, 1, 2, 1, 1)
        self.resultedImage = QtWidgets.QLabel(self.centralwidget)
        self.resultedImage.setGeometry(QtCore.QRect(1330, 270, 61, 21))
        self.resultedImage.setObjectName("resultedImage")
        self.firstImageEditTagsButton = QtWidgets.QPushButton(self.centralwidget)
        self.firstImageEditTagsButton.setGeometry(QtCore.QRect(80, 150, 81, 21))
        self.firstImageEditTagsButton.setObjectName("firstImageEditTagsButton")
        self.secondImageEditTagsButton = QtWidgets.QPushButton(self.centralwidget)
        self.secondImageEditTagsButton.setGeometry(QtCore.QRect(80, 530, 81, 21))
        self.secondImageEditTagsButton.setObjectName("secondImageEditTagsButton")
        self.resultedImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultedImageLabel.setGeometry(QtCore.QRect(1330, 240, 211, 16))
        self.resultedImageLabel.setObjectName("resultedImageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 18))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menumenu.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.xLabel.setText(_translate("MainWindow", "x"))
        self.p2Label.setText(_translate("MainWindow", "p2"))
        self.resultedImageChangeScaleButton.setText(_translate("MainWindow", "apply"))
        self.firstImageChangeScaleButton.setText(_translate("MainWindow", "apply"))
        self.p3Label.setText(_translate("MainWindow", "p3"))
        self.changeScaleLabel.setText(_translate("MainWindow", "change scale"))
        self.yLabel.setText(_translate("MainWindow", "y"))
        self.secondImageChangeScaleButton.setText(_translate("MainWindow", "apply"))
        self.cropImagesLabel.setText(_translate("MainWindow", "crop Images"))
        self.p1Label.setText(_translate("MainWindow", "p1"))
        self.imposingTypeNormal.setText(_translate("MainWindow", "normal"))
        self.imposingType3Points.setText(_translate("MainWindow", "3 points"))
        self.typrLabel.setText(_translate("MainWindow", "type"))
        self.imposingParametrsLabel.setText(_translate("MainWindow", "imposing parametrs"))
        self.firstImageCropButton.setText(_translate("MainWindow", "crop"))
        self.y1.setText(_translate("MainWindow", "y1"))
        self.y2.setText(_translate("MainWindow", "y2"))
        self.x2.setText(_translate("MainWindow", "x2"))
        self.saturationLabel.setText(_translate("MainWindow", "saturation"))
        self.resultedImageScaleLabel.setText(_translate("MainWindow", "resulted image"))
        self.secondImageScaleLabel.setText(_translate("MainWindow", "second image"))
        self.aplhaChanelLabel.setText(_translate("MainWindow", "aplha-chanel"))
        self.firstImageScaleLabel.setText(_translate("MainWindow", "first image"))
        self.x1Label.setText(_translate("MainWindow", "x1"))
        self.secondImageCropButton.setText(_translate("MainWindow", "crop"))
        self.firstImageCropLabel.setText(_translate("MainWindow", "first image "))
        self.resuledImageCropLabel.setText(_translate("MainWindow", "resulted image "))
        self.secondImageCropLabel.setText(_translate("MainWindow", "second image"))
        self.resultedImageCropButton.setText(_translate("MainWindow", "crop"))
        self.image2.setText(_translate("MainWindow", "choose file to load "))
        self.image2Label.setText(_translate("MainWindow", "image2"))
        self.image1.setText(_translate("MainWindow", "choose file to load "))
        self.image1Label.setText(_translate("MainWindow", "image1"))
        self.file1pathLabel.setText(_translate("MainWindow", "path to file1"))
        self.loadFilesButton.setText(_translate("MainWindow", "load files "))
        self.file1.setText(_translate("MainWindow", "path to file 2"))
        self.file1searchButton.setText(_translate("MainWindow", "search"))
        self.file2searchButton.setText(_translate("MainWindow", "search"))
        self.resultedImage.setText(_translate("MainWindow", "resulted image"))
        self.firstImageEditTagsButton.setText(_translate("MainWindow", "edit tags"))
        self.secondImageEditTagsButton.setText(_translate("MainWindow", "edit tags "))
        self.resultedImageLabel.setText(_translate("MainWindow", "resulted image"))
        self.menumenu.setTitle(_translate("MainWindow", "menu "))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))


